<a href="https://colab.research.google.com/github/Serin-k/class2021Spring/blob/main/20210426.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

함수 이름 phasor(amp, sr, dur, freq)
출력 return s(Signal), theta, t(time)

In [2]:
%matplotlib inline
from matplotlib import pyplot as plt
import IPython.display as ipd
import numpy as np
from scipy.signal import lfilter

# parameter setting
amp = 1          # range [0.0, 1.0]
sr = 10000       # sampling rate, Hz
dur = 0.5        # in seconds
freq = 100.0     # sine frequency, Hz
# amp: wave가 있을 때 높이. 진폭. 1로 설정하면 -1~1
# sr: sampling rate. 10000Hz로 한다는 것은 1초에 몇 개의 값(sample)이 들어가 있을 것인가. 얼마나 더 촘촘하게 할 것인가. 1초에 10000개의 숫자를 설정할 것이다
# dur: 얼마나 긴 sine wave를 만들 것인가
# freq(소리의 높낮이): 100으로 한다는 것은, 한번 왔다갔다하는 사이클(cycle)이 1초에 몇 개 있게 할 것인가. <-> sampling rate: 1초에 값들이 몇개가 있는가. freq: 반복되는 cycle이 몇개가 있는가 !!

In [4]:
def phasor(amp, sr, dur, freq):
  # generate time 각도값 phase와 시간을 싱크(sync)시켜야한다. 이때 사용되는 변수sr(sampling rate)
  # 1초에 값들이 몇개가 들어있는가: 시간을 얼마나 잘게 쪼갤 것인가. 
  # np.arange(1. 10000 * 1 + 1) 1~10000까지의 숫자를 만들어낸다. 
  # 시간 list t를 미리 만들어놓는다
  # 시간은 sin곡선의 입력으로 들어가지 못한당. 시간에 따른 각도로 바꿔줘야함
  t = np.arange(1, sr * dur+1)/sr

  # generate phase: sine wave 만들 때 각도값
  # 시간에 2파이를 곱하면 한바퀴짜리 sine wave가 만들어짐
  # 근데 우리는 freq100. 100바퀴짜리가 필요한거임
  theta = t * 2*np.pi * freq   

  # generate signal by cosine-phasor. sine wave. 입력값으로 radian 각도값
  # np.sin이라고 해야함. 
  # s = 사인곡선
  s = np.sin(theta)

  return s, theta, t

In [5]:
phasor(amp, sr, dur, freq)

(array([ 6.27905195e-02,  1.25333234e-01,  1.87381315e-01, ...,
        -1.25333234e-01, -6.27905195e-02,  1.96438672e-15]),
 array([6.28318531e-02, 1.25663706e-01, 1.88495559e-01, ...,
        3.14033602e+02, 3.14096434e+02, 3.14159265e+02]),
 array([1.000e-04, 2.000e-04, 3.000e-04, ..., 4.998e-01, 4.999e-01,
        5.000e-01]))